# Misawa Selectors Configuration

mansion:
  title: "h2.title"
  title_fallback: "h1"
  title_fallback_2: "h2"
  price: "dl.price dd"
  address: "div.data dl:nth-of-type(2) dd"
  root_xpath: "//ul[contains(@class, 'bukken-list')]/li/a/@href"
  table:
    selector: "table.outline"
    row: "tr"
    header: "th"
    value: "td"
  # Keys
  genkyo_key: "建物現況"
  hikiwatashi_key: "引渡（入居予定日）"
  biko_key: "備考制限事項"
  setsubi_key: "物件設備"
  kenri_key: "土地権利の種類"
  kenpei_key: "建ぺい率/容積率"
  youseki_key: "建ぺい率/容積率"
  parking_key: "駐車場　状況"
  kanri_keitai_key: "管理形態・方式"
  kanri_kaisya_key: "管理会社"
  shido_futan_key: "私道負担面積"

kodate:
  title: "h2.title"
  title_fallback: "h1"
  title_fallback_2: "h2"
  price: "dl.price dd"
  address: "div.data dl:nth-of-type(2) dd"
  root_xpath: "//ul[contains(@class, 'bukken-list')]/li/a/@href"
  table:
    selector: "table.outline"
    row: "tr"
    header: "th"
    value: "td"
  # Keys
  genkyo_key: "建物現況"
  hikiwatashi_key: "引渡（入居予定日）"
  biko_key: "備考制限事項"
  setsubi_key: "物件設備"
  kenri_key: "土地権利の種類"
  kenpei_key: "建ぺい率/容積率"
  youseki_key: "建ぺい率/容積率"
  parking_key: "駐車場　状況"
  shido_futan_key: "私道負担面積"
  # New Keys
  neighborhood_key: "周辺施設"
  school_district_key: "学区"
  urban_planning_key: "都市計画"
  transaction_type_key: "取引態様"
  kakunin_bango_key: "建築確認番号"
  setback_key: "セットバック"

tochi:
  title: "h2.title"
  title_fallback: "h1"
  title_fallback_2: "h2"
  price: "dl.price dd"
  address: "div.data dl:nth-of-type(2) dd"
  root_xpath: "//ul[contains(@class, 'bukken-list')]/li/a/@href"
  table:
    selector: "table.outline"
    row: "tr"
    header: "th"
    value: "td"
  # Keys
  genkyo_key: "現況"
  hikiwatashi_key: "引渡（入居予定日）"
  biko_key: "備考制限事項"
  setsubi_key: "物件設備"
  kenri_key: "土地権利の種類"
  kenpei_key: "建ぺい率/容積率"
  youseki_key: "建ぺい率/容積率"
  parking_key: "駐車場　状況"
  shido_futan_key: "私道負担面積"
  # New Keys
  neighborhood_key: "周辺施設"
  school_district_key: "学区"
  urban_planning_key: "都市計画"
  transaction_type_key: "取引態様"
  kakunin_bango_key: "建築確認番号"
  setback_key: "セットバック"

investment:
  title: "h2.title"
  title_fallback: "h1"
  title_fallback_2: "h2"
  price: "dl.price dd"
  address: "div.data dl:nth-of-type(2) dd"
  root_xpath: "//ul[contains(@class, 'bukken-list')]/li/a/@href"
  table:
    selector: "table.outline"
    row: "tr"
    header: "th"
    value: "td"
  # Keys
  genkyo_key: "現況"
  hikiwatashi_key: "引渡（入居予定日）"
  biko_key: "備考制限事項"
  setsubi_key: "物件設備"
  kenri_key: "土地権利の種類"
  kenpei_key: "建ぺい率/容積率"
  youseki_key: "建ぺい率/容積率"
  parking_key: "駐車場　状況"
  shido_futan_key: "私道負担面積"
  # New Keys
  neighborhood_key: "周辺施設"
  school_district_key: "学区"
  urban_planning_key: "都市計画"
  transaction_type_key: "取引態様"
  kakunin_bango_key: "建築確認番号"
  setback_key: "セットバック"
