# Mitsui Selectors Configuration
# CSS selectors for parsing Mitsui property pages


mansion:
  # Basic selectors
  title: "h1.headline1"
  price: ".price-value"
  # Navigation XPaths
  root_xpath: "//li/a[contains(@href,'/buy/mansion/prefecture/')]/@href"
  area_xpath: "//a[contains(@href,'/buy/mansion/prefecture/') and contains(@href, 'city/') and @class='link']/@href"
  property_list_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/mansion/bkdetail/')]/@href"
  next_page_xpath: "//a[contains(@class, 'pagination-next') or contains(@class, 'is-next')]/@href"
  property_links_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/mansion/bkdetail/') and not (contains(@href, '/inquiry/'))]/@href"
  
  # Table selectors
  table:
    header: "td.table-header.label"
    value: "td.table-data"
  
  # Field mappings (label -> model field name)
  field_mappings:
    専有面積: "senyuMensekiStr"
    築年月: "chikunengetsuStr"
    管理費等: "kanrihiStr"
    修繕積立金: "syuzenTsumitateStr"
    間取り: "madori"
    バルコニー: "barukoniMensekiStr"
    管理形態: "kanriKeitai"
    所在階 / 階建: "kaisu"

kodate:
  # Basic selectors
  title: "h1.headline1"
  price: ".price-value"
  # Navigation XPaths
  root_xpath: "//li/a[contains(@href,'/buy/kodate/prefecture/')]/@href"
  area_xpath: "//a[contains(@href,'/buy/kodate/prefecture/') and contains(@href, 'city/') and @class='link']/@href"
  property_list_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/kodate/bkdetail/')]/@href"
  next_page_xpath: "//a[contains(@class, 'pagination-next') or contains(@class, 'is-next')]/@href"
  property_links_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/kodate/bkdetail/') and not (contains(@href, '/inquiry/'))]/@href"
  
  # Table selectors
  table:
    header: "td.table-header.label"
    value: "td.table-data"
  
  # Field mappings
  field_mappings:
    土地面積: "tochiMensekiStr"
    建物面積: "tatemonoMensekiStr"
    築年月: "chikunengetsuStr"
    間取り: "madori"
    構造: "kouzou"

tochi:
  # Basic selectors
  title: "h1.headline1"
  price: ".price-value"
  # Navigation XPaths
  root_xpath: "//li/a[contains(@href,'/buy/tochi/prefecture/')]/@href"
  area_xpath: "//a[contains(@href,'/buy/tochi/prefecture/') and contains(@href, 'city/') and @class='link']/@href"
  property_list_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/tochi/bkdetail/')]/@href"
  next_page_xpath: "//a[contains(@class, 'pagination-next') or contains(@class, 'is-next')]/@href"
  property_links_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/buy/tochi/bkdetail/') and not (contains(@href, '/inquiry/'))]/@href"
  
  # Table selectors
  table:
    header: "td.table-header.label"
    value: "td.table-data"
  
  # Field mappings
  field_mappings:
    土地面積: "tochiMensekiStr"
    用途地域: "youto"
    建ぺい率: "kenpeiritsu"
    容積率: "yousekritsu"

investment:
  # Basic selectors
  title: "h1.headline1"
  price: ".price-value"
  # Navigation XPaths - Corrected to /buy/tohshi/ as per user instruction
  root_xpath: "//a[starts-with(@href,'prefecture/')]/@href"
  area_xpath: "//a[contains(@href,'/buy/tohshi/prefecture/') and contains(@href, 'city/') and @class='link']/@href"
  property_list_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/bkdetail/')]/@href"
  next_page_xpath: "//a[contains(@class, 'pagination-next') or contains(@class, 'is-next')]/@href"
  property_links_xpath: "//div[contains(@class,'property-index-card')]//a[contains(@href,'/bkdetail/') and not (contains(@href, '/inquiry/'))]/@href"
  
  # Table selectors
  table:
    header: "td.table-header.label"
    value: "td.table-data"
  
  # Field mappings
  field_mappings:
    専有面積: "senyuMensekiStr"
    築年月: "chikunengetsuStr"
    管理費等: "kanrihiStr"
    修繕積立金: "syuzenTsumitateStr"
    間取り: "madori"
    想定利回り: "souteiRimawari"
