# Sumifu Selectors Configuration
# CSS selectors for parsing Sumifu property pages

mansion:
  # Basic selectors
  title: "h1.heading-1" # Fallback: "h1"
  price: "dl#s_summaryPrice dd p em"
  address: "div#bukkenDetailBlock div.itemInfo dl.address dd"
  
  # List page selectors
  next_page: "#searchCondition ul.pagination li:last-child a"
  property_links: "a.property-info-anchor"
  
  root_xpath: ""
  region_xpath: '//a[contains(@href,"/mansion/area_")]/@href'
  area_xpath: '//a[contains(@href,"/mansion/area_") and contains(@href,"/list_")]/@href'
  property_list_xpath: '//div[@id="searchResultBlock"]//a[contains(@href, "/mansion/detail_")]/@href'

  # Table selectors
  table:
    selector: "table.table-detail"
    header: "th"
    value: "td"

kodate:
  title: "h1.heading-1"
  price: "dl#s_summaryPrice dd p em"
  address: "div#bukkenDetailBlock div.itemInfo dl.address dd"
  next_page: "#searchCondition ul.pagination li:last-child a"
  property_links: "a.property-info-anchor"
  
  root_xpath: ""
  region_xpath: '//a[contains(@href,"/kodate/area_")]/@href'
  area_xpath: '//a[contains(@href,"/kodate/area_") and contains(@href,"/list_")]/@href'
  property_list_xpath: '//div[@id="searchResultBlock"]//a[contains(@href, "/kodate/detail_")]/@href'

  table:
    selector: "table.table-detail"
    header: "th"
    value: "td"

tochi:
  title: "h1.heading-1"
  price: "dl#s_summaryPrice dd p em"
  address: "div#bukkenDetailBlock div.itemInfo dl.address dd"
  next_page: "#searchCondition ul.pagination li:last-child a"
  property_links: "a.property-info-anchor"
  
  root_xpath: ""
  region_xpath: '//a[contains(@href,"/tochi/area_")]/@href'
  area_xpath: '//a[contains(@href,"/tochi/area_") and contains(@href,"/list_")]/@href'
  property_list_xpath: '//div[@id="searchResultBlock"]//a[contains(@href, "/tochi/detail_")]/@href'

  table:
    selector: "table.table-detail"
    header: "th"
    value: "td"

investment:
  title: "h1.heading-1"
  price: "table.table-detail tr" # Special handling in parser
  address: "所在地" # Mapping key
  next_page: "次へ" # Text search
  property_links: "a[href*='/pro/detail_']"
  property_links_fallback: ".bukken-list .article-card a"
  region_xpath: '//a[contains(@href,"/pro/area_")]/@href'
  area_xpath: '//a[contains(@href,"/pro/area_") and contains(@href,"/list_")]/@href'
  property_list_xpath: '//div[@id="searchResultBlock" or @class="bukken-list"]//a[contains(@href, "/pro/detail_")]/@href'
  table:
    selector: "table.table-detail"
    header: "th"
    value: "td"
