# Tokyu Selectors Configuration
# CSS selectors for parsing Tokyu property pages

mansion:
  title: "h1.o-detail-header__headline"
  price: "table.m-status-table__wrapper dl dd p span"
  address: "table.m-status-table__wrapper dl dd a"
  
  root_xpath: ""
  area_xpath: ""
  next_page_xpath: "(//div[@class=\"m-page-navigation__inner\"])[1]/a[@class=\"m-page-navigation__next iconfont-livable-arrow_right\"]/@href"
  property_links_xpath: "//a[@class=\"o-product-list__menu-link rec_detail_link\" and contains(@href,\"/mansion/\")]/@href"
  
  table:
    selector: "div.m-status-table__wrapper table" # Some sections use dl/dt/dd, others use table
    header: "dt"
    value: "dd"

kodate:
  title: "h1.o-detail-header__headline"
  price: "table.m-status-table__wrapper dl dd p span"
  address: "table.m-status-table__wrapper dl dd a"
  
  root_xpath: ""
  area_xpath: ""
  next_page_xpath: "(//div[@class=\"m-page-navigation__inner\"])[1]/a[@class=\"m-page-navigation__next iconfont-livable-arrow_right\"]/@href"
  property_links_xpath: "//a[@class=\"o-product-list__menu-link rec_detail_link\" and contains(@href,\"/kodate/\")]/@href"
  table:
    selector: "div.m-status-table__wrapper"
    header: "dt"
    value: "dd"

tochi:
  title: "h1.o-detail-header__headline"
  price: "table.m-status-table__wrapper dl dd p span"
  address: "table.m-status-table__wrapper dl dd a"
  
  root_xpath: ""
  area_xpath: ""
  next_page_xpath: "(//div[@class=\"m-page-navigation__inner\"])[1]/a[@class=\"m-page-navigation__next iconfont-livable-arrow_right\"]/@href"
  property_links_xpath: "//a[@class=\"o-product-list__menu-link rec_detail_link\" and contains(@href,\"/tochi/\")]/@href"
  table:
    selector: "div.m-status-table__wrapper"
    header: "dt"
    value: "dd"

investment:
  title: "h1"
  price: ".price"
  address: "所在地"
  next_page: "次へ"
  property_links: "a[href*='/fudosan-toushi/C']"
  table:
    selector: "dl"
    header: "dt"
    value: "dd"
